In [10]:
#array iteration
import numpy as np
ar=np.array(
    [
        [1,2],
        [3,4]
    ]
)
for i in ar:
    for x in i:
        print(x)

1
2
3
4


In [11]:
#nditer
arr=np.array([[1,2],[3,4]])
for i in np.nditer(arr,order='F'):
    print(i)

1
3
2
4


In [12]:
#ndenumerate
arr=np.array([[1,2],[3,4]])
for index,element in np.ndenumerate(arr):
    print(index,element)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


In [16]:
arr=np.zeros(5,dtype=int)
arr.fill(10)
print(arr)

[10 10 10 10 10]


In [17]:
#indexing and slicing
ar=np.array([1,2,3,4,5])
print("BEFORE")
print(ar)
print("AFTER")
ar[0:4]=[30,40,50,60]
print(ar)

BEFORE
[1 2 3 4 5]
AFTER
[30 40 50 60  5]


In [19]:
#put method
ar=np.array([1,2,3,4,54,5])
np.put(ar,[3,4,0],[10,40,29])
print(ar)

[29  2  3 10 40  5]


In [23]:
#boolean indexing
ar=np.array([1,2,3,4,54,5])
ar[ar==1]=8
print(ar)

[ 8  2  3  4 54  5]
