In [71]:
import numpy as np
ar=np.array([1,3,4,5,6,7])
print(ar.shape)
print(ar.ndim)
print(ar.size)
print(ar.dtype)
print(ar.itemsize)
print(ar.data)
print(ar.strides)
print(ar.flags)

(6,)
1
6
int32
4
(4,)
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [72]:
#ndarray attributes
import numpy as np
ar=np.array([1,3,4,5])
print(ar)
print(ar.reshape(1,4))
print(ar.sum())
print(ar.mean())
print(ar.min())
print(ar.max())
print(ar.argmax())
print(ar.argmin())

[1 3 4 5]
[[1 3 4 5]]
13
3.25
1
5
3
0


In [73]:
#array creation in different ways
#numpy.empty(shape,dtype=float,order='C')
a=np.empty((4,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [74]:
#numpy.ones(shape,dtype=float,order='C')
a2=np.ones((4,4),dtype=int)
a2.fill(8)
print(a2)

[[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]


In [75]:
#numpy.zeros(shape,dtype=float,order='C')
a1=np.zeros((4,4),dtype=int)
print(a1)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [76]:
#asarray
data=(1,2,3,4,5)
arr=np.asarray(data)
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [77]:
#Broadcsting
a1=np.array([
   [1,3,4]
])
a2=np.array([
    [3,4,5],
    [1,2,3],
    [4,5,6],
    [6,7,8]
])
print(a1+a2)
print(a1+10)

[[ 4  7  9]
 [ 2  5  7]
 [ 5  8 10]
 [ 7 10 12]]
[[11 13 14]]


In [78]:
#frombuffer
#numpy.frombuffer(buffer_object,dtype=float,count=-1,offset=0)
#buffer:the buffer object,you want to convert into array
#dtype:resulted data type of an array
#count:how much item you want to fetch from buffer object?if set to-1,it will read all items
#offset:buffer object's starting position default is 0 index

In [79]:
import numpy as np
buffer_obj=b'\x010\x011\x056\x067'
ar=np.frombuffer(buffer_obj,dtype=np.uint8)
print(ar)

[ 1 48  1 49  5 54  6 55]


In [80]:
#fromiter
#numpy.fromiter(iterable_object,dtype,count=-1)
lst=[1,2,3,4,5]
ar=np.fromiter(lst,dtype=int)
print(ar)
print(type(ar))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [81]:
#np.arrange(start,stop,step,dtype=None)
import numpy as np
ar=np.arange(0,10)
print(ar)

[0 1 2 3 4 5 6 7 8 9]


In [82]:
#array from numerical ranges
values=np.linspace(0,1,num=10)
print(values)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [84]:
#array from numerical ranges
values=np.logspace(-5,10,num=4)
print(values)

[1.e-05 1.e+00 1.e+05 1.e+10]
