In [2]:
#reshape
#new_ar=numpy.reshape(array,new_shape)
import numpy as np
ar=np.array([1,2,3,4])
ar1=np.reshape(ar,(2,2))
print(ar1)

[[1 2]
 [3 4]]


In [6]:
#flat
ar=np.array(
    [
        [1,2,4],
        [3,4,5]
    ]
)
flat_obj=ar.flat
for i in flat_obj:
    print(i)

1
2
4
3
4
5


In [7]:
#new_ar=original_ar.flatten()
ar=np.array(
    [
        [1,2,4],
        [3,4,5]
    ]
)
new_ar=ar.flatten()
print(new_ar)

[1 2 4 3 4 5]


In [8]:
#mew_ar=original_ar.ravel()
ar=np.array([
    [1,2,3],
    [2,3,4]
])
new_ar=ar.ravel()
print(new_ar)

[1 2 3 2 3 4]


In [10]:
#concatenate
#np.concatenate((a,b),axis=0)
a=np.array([1,2,3])
b=np.array([4,5,6])
new_ar=np.concatenate((a,b),axis=0)
print(new_ar)

[1 2 3 4 5 6]


In [12]:
#transpose
a=np.array([[1,2,3,4],[5,6,7,8]])
ar=np.transpose(a)
print(ar)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [19]:
#split:sub_array split(array_name,number of sub_array)
a=np.array([1,2,3,4])
sub_ar=np.split(a,4)
print(sub_ar)

[array([1]), array([2]), array([3]), array([4])]


In [27]:
#resize
#new_ar=np.resize(array,desired_shape)
a1=np.array([1,2,3])
a2=np.resize(a1,4)
print(a2)

[1 2 3 1]


In [29]:
#append
a1=np.array([1,2,3])
a2=np.append(a1,4)
print(a2)

[1 2 3 4]


In [32]:
#insert
a1=np.array([1,2,3])
a2=np.insert(a1,3,4)
print(a2)


[1 2 3 4]


In [37]:
#delete
a1=np.array([1,2,3])
a2=np.delete(a1,0)
print(a2)

[2 3]


In [38]:
#unique
a1=np.array([1,2,3])
a2=np.unique(a1,4)
print(a2)

(array([1, 2, 3]), array([0, 1, 2], dtype=int64))
