In [3]:
import numpy as np
print(np.array([1,2,3]))


[1 2 3]


In [4]:
import numpy as np
n,m=list(map(int,input().split()))
m1=[]
for i in range(n):
    m1.append(list(map(int,input().split())))
m2=[]
for i in range(n):
    m2.append(list(map(int,input().split())))
a=np.array(m1)
b=np.array(m2)

print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.floor_divide(a,b))
print(np.mod(a,b))
print(np.power(a,b))


ValueError: not enough values to unpack (expected 2, got 1)

In [ ]:
import numpy
print(numpy.__version__)

1.26.4


In [ ]:
import numpy as np
carr=np.array([
    [[1,2]],
    [[3,4]],
    [[5,6,7]]
])
print(carr)
print(carr.ndim)
print(carr.shape)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 1) + inhomogeneous part.

In [6]:
import numpy as np
myarr=np.array([12,3,44,123,53,64],dtype='f')
print(myarr[-1])

64.0


In [14]:

import numpy as np

ar = np.array([
    [1, 3],
    [6, 4]
])

print(ar[1][0])


6


In [25]:
import numpy as np
ar=np.array([5,2,1,4,3])
print(ar.mean())

3.0


In [27]:
#data types
import numpy as np
ar=np.array([5,2,1,4,3],dtype=np.int32)
print(ar)

[5 2 1 4 3]


In [2]:
#timedelta-it is a data type in numpy that represents the difference between two dates or times
import numpy as np
date1=np.datetime64('2024-07-06')
date2=np.datetime64('2023-07-05')
time_difference=date1-date2
print(time_difference)

367 days


In [3]:
#astype used for datatype conversion
ar=np.array([5,6,7,4])
ar_float=ar.astype(np.float64)
print(ar_float)

[5. 6. 7. 4.]


In [ ]:
#array attributes
