In [3]:
#string functioins
#add()
import numpy as np
ar=np.array(['learn','numpy','with'])
new_ar=np.char.add(ar,'codeguy')
print(new_ar)

['learncodeguy' 'numpycodeguy' 'withcodeguy']


In [4]:
#title()
ar=np.array(['learn','numpy','with'])
new_ar=np.char.title(ar)
print(new_ar)

['Learn' 'Numpy' 'With']


In [6]:
#lower()
ar=np.array(['Learn','Numpy','With'])
new_ar=np.char.lower(ar)
print(new_ar)

['learn' 'numpy' 'with']


In [7]:
#upper()
ar=np.array(['Learn','Numpy','With'])
new_ar=np.char.upper(ar)
print(new_ar)

['LEARN' 'NUMPY' 'WITH']


In [8]:
#strip
ar=np.array([' Learn',' Numpy',' With'])
new_ar=np.char.strip(ar)
print(new_ar)

['Learn' 'Numpy' 'With']


In [10]:
#split
ar=np.array(['Learn','Numpy','With'])
new_ar=np.char.split(ar,'e')
print(new_ar)

[list(['L', 'arn']) list(['Numpy']) list(['With'])]


In [13]:
#join
ar=np.array(['Learn','Numpy','With'])
new_ar=np.char.join('-',ar)
print(new_ar)

['L-e-a-r-n' 'N-u-m-p-y' 'W-i-t-h']


In [17]:
#replace
#numpy.char.replace(arr,ol,new,count=None)
ar=np.array(['Learn','Numpy','With'])
new_ar=np.char.replace(ar,'a','y',count=1)
print(new_ar)

['Leyrn' 'Numpy' 'With']


In [20]:
#mathematical function
angles=np.array([0,1,2,3])
radian=np.radians(angles)
print(radian)
print(np.sin(radian))
print(np.cos(radian))
print(np.tan(radian))
print(np.arcsin(radian))
print(np.arccos(radian))
print(np.arctan(radian))

[0.         0.01745329 0.03490659 0.05235988]
[0.         0.01745241 0.0348995  0.05233596]
[1.         0.9998477  0.99939083 0.99862953]
[0.         0.01745506 0.03492077 0.05240778]
[0.         0.01745418 0.03491368 0.05238383]
[1.57079633 1.55334215 1.53588265 1.5184125 ]
[0.         0.01745152 0.03489242 0.05231211]


In [33]:
ar=np.array([1,2,3])
print(np.exp(ar))
print(np.sqrt(ar))
print(np.power(ar,2))
print(np.absolute(ar))
print(np.log(ar))
print(np.log10(ar))
print(np.around(ar))
print(np.degrees(ar))


[ 2.71828183  7.3890561  20.08553692]
[1.         1.41421356 1.73205081]
[1 4 9]
[1 2 3]
[0.         0.69314718 1.09861229]
[0.         0.30103    0.47712125]
[1 2 3]
[ 57.29577951 114.59155903 171.88733854]
