In [2]:
#BITWISE AND 
import numpy as np
a=np.array([1,2,3],dtype=np.uint8)
b=np.array([4,5,6],dtype=np.uint8)
bitwise_and=np.bitwise_and(a,b)
print(bitwise_and)

[0 0 2]


In [3]:
#BITWISE OR
import numpy as np
a=np.array([1,2,3],dtype=np.uint8)
b=np.array([4,5,6],dtype=np.uint8)
bitwise_or=np.bitwise_or(a,b)
print(bitwise_or)

[5 7 7]


In [10]:
#BITWISE NOT
import numpy as np
a=np.array([1,2,3],dtype=np.uint8)
b=np.array([4,5,6],dtype=np.uint8)
bitwise_not=np.bitwise_not(a)
print(bitwise_not)

[254 253 252]


In [14]:
#BITWISE LEFT SHIFT
import numpy as np
a=np.array([1,2,3],dtype=np.uint8)
b=np.array([4,5,6],dtype=np.uint8)
bitwise_left=np.left_shift(a,2)
print(bitwise_left)

[ 4  8 12]


In [17]:
#BITWISE RIGHT SHIFT
import numpy as np
a=np.array([1,2,3],dtype=np.uint8)
b=np.array([4,5,6],dtype=np.uint8)
bitwise_right=np.right_shift(a,1)
print(bitwise_right)

[0 1 1]
