In [2]:
#sort
import numpy as np
ar=np.array(
    [1,0,5,3]
)
#print(np.sort(ar,axis=1))
#argsort:result is an array of indices that can be used to reorderthe original array
print(np.argsort(ar))
#searchsorted:find indices where elements should be inserted to maintain orderin sorted array
print(np.searchsorted(ar,7))



[1 0 3 2]
4


In [3]:
#partition
ar=np.array([1,0,5,3])
partitioned_ar=np.partition(ar,3)
print(partitioned_ar)
argpartitioned_ar=np.argpartition(ar,3)
print(argpartitioned_ar)


[0 1 3 5]
[1 0 3 2]


In [5]:
#where:this function returns the indices of elements in a array that satisfy a given condition
arr=np.array([1,2,3,4,5])
print(np.where(arr>2))

(array([2, 3, 4], dtype=int64),)


In [6]:
#argwhere:this function returns the indices of elements in an array that satisfy a given condition
arr=np.array([1,2,3,4,5])
print(np.argwhere(arr>2))

[[2]
 [3]
 [4]]


In [7]:
#nonzero:this function returns the indices of non zero elements in an array
arr=np.array([1,0,2,0,3,0])
print(np.nonzero(arr))

(array([0, 2, 4], dtype=int64),)


In [9]:
#extract:this function returns the elements of an array that satisfy a given condition
ar=np.array([1,2,3,4,5,6,7,8,9])
print(np.extract(ar<3,ar))

[1 2]


In [10]:
#filtration
ar=np.array([1,2,3,4,5,6,7,8,9])
print(ar[ar>6])

[7 8 9]


In [13]:
#where
ar=np.array([1,2,3,4,5,6,7,8,9])
print(np.where(ar>3,ar,7))

[7 7 7 4 5 6 7 8 9]


In [14]:
#compress:this function filters an array based on boolean mask
ar=np.array([1,2,3,4,5,6,7,8,9])
print(np.compress(ar<3,ar))



[1 2]
