In [12]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.floor_divide(a,b))
print(np.mod(a,b))
print(np.negative(a))
print(np.remainder(b,a))

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[0 0 0]
[1 2 3]
[-1 -2 -3]
[0 1 0]


In [31]:
a=np.array([1,2,3])
print(np.mean(a))
print(np.median(a))
print(np.var(a))
print(np.std(a))
print(np.min(a))
print(np.max(a))
print(np.sum(a))
print(np.prod(a))
print(np.argmin(a))
print(np.argmax(a))
print(np.count_nonzero(a))
print(np.unique(a))
print(np.bincount(a))
print(np.cumsum(a))
print(np.cumprod(a))

2.0
2.0
0.6666666666666666
0.816496580927726
1
3
6
6
0
2
3
[1 2 3]
[0 1 1 1]
[1 3 6]
[1 2 6]
