In [1]:
#view:a view of an array can be created using slicing method
import numpy as np
ar=np.array([4,5,3,7,8])
print(ar[:4]) 


[4 5 3 7]


In [2]:
#create view
ar=np.array([[1,2,3],
             [4,5,6]])
view=ar.T
view[0,1]=99
print(view)

[[ 1 99]
 [ 2  5]
 [ 3  6]]


In [3]:
#reshaping(view):
arr=np.array([1,2,3,4,5,6])
#Reshaping the 1D array to a 2D array to create a view
print(arr.reshape(2,3))

[[1 2 3]
 [4 5 6]]


In [4]:
#copy:it is used to create a new array object from an existing array having same values,but stored at a different memory location
ar1=np.array([3,2,1,4,8])
ar2=ar1.copy()
ar2[0]=90
print(ar1)
print(ar2)

[3 2 1 4 8]
[90  2  1  4  8]


In [7]:
arr=np.array([10,20,30,40,50])
#using fancy indexing to create a copy based on the index array
indices=[1,3]
cpy=arr[indices]
cpy[0]=99
print(cpy)
print(arr)

[99 40]
[10 20 30 40 50]
